# Generated by Django 5.2.7 on 2025-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-position']},
        ),
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='places'),
        ),
    ]
