# Generated by Django 5.2.7 on 2025-10-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_photo_options_photo_position_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['position']},
        ),
    ]
