# Generated by Django 5.2.7 on 2025-10-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_photo_image_alter_photo_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
