# Generated by Django 5.2.7 on 2025-10-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
