# Generated by Django 5.2.7 on 2025-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_photo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(max_length=3000, verbose_name='Полное описание'),
        ),
    ]
